EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'R$O$TG$DDL')) THEN
		EXECUTE STATEMENT 'DROP TRIGGER R$O$TG$DDL';
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$TRIGGERS WHERE RDB$TRIGGER_NAME = 'R$O$TG$TRANSACAO_COMMIT')) THEN
		EXECUTE STATEMENT 'DROP TRIGGER R$O$TG$TRANSACAO_COMMIT';
END^

EXECUTE BLOCK AS
DECLARE Nome VARCHAR(31);
BEGIN
	FOR 
		SELECT RDB$TRIGGER_NAME FROM RDB$TRIGGERS
		 WHERE RDB$TRIGGER_NAME LIKE 'R$O$TG$%'
		   AND RDB$RELATION_NAME IS NOT NULL
		   AND RDB$TRIGGER_TYPE BETWEEN 1 AND 114
		   AND RDB$SYSTEM_FLAG = 0
		INTO :Nome
	DO
		EXECUTE STATEMENT 'DROP TRIGGER ' || :Nome;
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$PROCEDURES WHERE RDB$PROCEDURE_NAME = 'R$O$SP$CRIA_GATILHO_REP_INSERT')) THEN
		EXECUTE STATEMENT 'DROP PROCEDURE R$O$SP$CRIA_GATILHO_REP_INSERT';
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$PROCEDURES WHERE RDB$PROCEDURE_NAME = 'R$O$SP$CRIA_GATILHO_REP_UPDATE')) THEN
		EXECUTE STATEMENT 'DROP PROCEDURE R$O$SP$CRIA_GATILHO_REP_UPDATE';
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$PROCEDURES WHERE RDB$PROCEDURE_NAME = 'R$O$SP$CRIA_GATILHO_REP_DELETE')) THEN
		EXECUTE STATEMENT 'DROP PROCEDURE R$O$SP$CRIA_GATILHO_REP_DELETE';
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$PROCEDURES WHERE RDB$PROCEDURE_NAME = 'R$O$SP$REMOVE_GATILHO_REP')) THEN
		EXECUTE STATEMENT 'DROP PROCEDURE R$O$SP$REMOVE_GATILHO_REP';
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$PROCEDURES WHERE RDB$PROCEDURE_NAME = 'R$O$SP$REMOVE_TRANSACAO')) THEN
		EXECUTE STATEMENT 'DROP PROCEDURE R$O$SP$REMOVE_TRANSACAO';
END^

EXECUTE BLOCK AS
DECLARE Nome VARCHAR(31);
BEGIN
	FOR 
		SELECT RDB$EXCEPTION_NAME FROM RDB$EXCEPTIONS 
		WHERE RDB$EXCEPTION_NAME LIKE 'R$O$EX$%'
		  AND RDB$SYSTEM_FLAG = 0
		INTO :Nome
	DO
		EXECUTE STATEMENT 'DROP EXCEPTION ' || :Nome;
END^

RECONNECT^

EXECUTE BLOCK AS
BEGIN
	RDB$SET_CONTEXT('USER_SESSION', 'R$C$VAR$REPLICADOR', TRUE);
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'R$O$GTT$PARAMETRO')) THEN
		EXECUTE STATEMENT 'DROP TABLE R$O$GTT$PARAMETRO';
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'R$O$GTT$COMANDO')) THEN
		EXECUTE STATEMENT 'DROP TABLE R$O$GTT$COMANDO';
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'R$O$TB$PARAMETRO')) THEN
		EXECUTE STATEMENT 'DROP TABLE R$O$TB$PARAMETRO';
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'R$O$TB$COMANDO')) THEN
		EXECUTE STATEMENT 'DROP TABLE R$O$TB$COMANDO';
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'R$O$TB$TRANSACAO_DESTINO')) THEN
		EXECUTE STATEMENT 'DROP TABLE R$O$TB$TRANSACAO_DESTINO';
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'R$O$TB$TRANSACAO')) THEN
		EXECUTE STATEMENT 'DROP TABLE R$O$TB$TRANSACAO';
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'R$O$TB$DESTINO')) THEN
		EXECUTE STATEMENT 'DROP TABLE R$O$TB$DESTINO';
END^

EXECUTE BLOCK AS
DECLARE NOME VARCHAR(31);
BEGIN
	FOR 
		SELECT RDB$GENERATOR_NAME FROM RDB$GENERATORS
		WHERE RDB$GENERATOR_NAME SIMILAR TO 'R$O$SQ$%' 
		  AND RDB$SYSTEM_FLAG = 0
		INTO :NOME
	DO
		EXECUTE STATEMENT 'DROP SEQUENCE ' || NOME;
END^
