EXECUTE BLOCK AS
BEGIN
	RDB$SET_CONTEXT('USER_SESSION', 'R$C$VAR$REPLICADOR', TRUE);
END^

EXECUTE BLOCK AS
DECLARE NOME VARCHAR(31);
BEGIN
	IF (EXISTS(SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'R$D$TB$GATILHOS')) THEN
	BEGIN
		FOR	
			EXECUTE STATEMENT 'SELECT NOME FROM R$D$TB$GATILHOS' INTO :NOME
		DO 
			EXECUTE STATEMENT 'ALTER TRIGGER ' || NOME || ' ACTIVE';	
	END
END^

EXECUTE BLOCK AS
DECLARE TABELA VARCHAR(31);
DECLARE CAMPO VARCHAR(31);
DECLARE SEQUENCIA VARCHAR(31);
DECLARE VALOR BIGINT;
BEGIN
	FOR 	
		SELECT RDB$RELATION_NAME, RDB$FIELD_NAME, RDB$GENERATOR_NAME 
		FROM RDB$RELATION_FIELDS
		WHERE RDB$IDENTITY_TYPE = 1
		INTO :TABELA, :CAMPO, SEQUENCIA
	DO
	BEGIN
		EXECUTE STATEMENT 'SELECT MAX(' || :CAMPO || ') FROM ' || :TABELA INTO :VALOR;
		EXECUTE STATEMENT 'ALTER SEQUENCE ' || :SEQUENCIA || ' RESTART WITH ' || COALESCE(:VALOR, 0);
	END
END^

EXECUTE BLOCK AS
BEGIN
	IF (EXISTS(SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'R$D$TB$GATILHOS')) THEN
		EXECUTE STATEMENT 'DROP TABLE R$D$TB$GATILHOS';
END^

EXECUTE BLOCK AS
DECLARE NOME VARCHAR(31);
BEGIN
	FOR
		SELECT RDB$TRIGGER_NAME FROM RDB$TRIGGERS
		WHERE RDB$TRIGGER_NAME SIMILAR TO 'R$D$TG$%'
		  AND RDB$SYSTEM_FLAG = 0
		INTO :NOME
	DO
		EXECUTE STATEMENT 'DROP TRIGGER ' || NOME;
END^

EXECUTE BLOCK AS
DECLARE NOME VARCHAR(31);
BEGIN
	FOR 
		SELECT RDB$EXCEPTION_NAME FROM RDB$EXCEPTIONS
		WHERE RDB$EXCEPTION_NAME SIMILAR TO 'R$D$EX$%'
		  AND RDB$SYSTEM_FLAG = 0
		INTO :NOME
	DO
		EXECUTE STATEMENT 'DROP EXCEPTION ' || NOME;
END^